#server.port = 9001
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry = true
#eureka.client.service-url.defaultZone = http://localhost:8761/eureka/
#eureka.instance.hostname = localhost
#
#spring.application.name = DEPARTMENT-SERVICE

server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/